# Generated by Django 2.1.3 on 2018-11-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.UUIDField(help_text='ID unico de usuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('cedula', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=40)),
                ('habilidades', models.TextField()),
                ('correo', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
