# Generated by Django 2.1.3 on 2018-11-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navar', '0002_auto_20181129_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id_actividad',
            field=models.AutoField(help_text='ID unico de actividad', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='id_tarea',
            field=models.AutoField(help_text='ID unico de tarea', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='caso',
            name='id_caso',
            field=models.AutoField(help_text='ID del caso', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_comentario',
            field=models.AutoField(help_text='ID unico de comentario', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entradasalida',
            name='id_tarea',
            field=models.AutoField(help_text='ID unico de tarea', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='id_paquete',
            field=models.AutoField(help_text='ID unico de paquete', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='id_parametro',
            field=models.AutoField(help_text='ID unico de parametro', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='id_propuesta',
            field=models.AutoField(help_text='ID de la solicitud', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='id_requerimiento',
            field=models.AutoField(help_text='ID unico de requerimiento', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='id_tarea',
            field=models.AutoField(help_text='ID unico de tarea', primary_key=True, serialize=False),
        ),
    ]
